---

name: Mutation Testing
permissions:
  contents: read

on: [push, pull_request]

jobs:
  mutate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1

      - run: cpanm --skip-satisfied --installdeps .
      - run: prove -l t/

      - run: echo "$(pwd)/local/bin" >> $GITHUB_PATH

      - run: |
          perl Makefile.PL
          make install

      - run: perl -Ilib -Iblib/lib bin/app-test-generator-mutate \
         --lib lib \
         --json mutation.json \
         --html mutation_html
#        --min-score 85 \
